#!/bin/bash

echo "COMPILING..."
xcodebuild -target SuccessionRestore -xcconfig compile32.xcconfig -configuration Debug >> /dev/null
mv ./Build/Debug-iphoneos/SuccessionRestore.app ./
mv ./SuccessionRestore32 ./SuccessionRestore.app/SuccessionRestore32
ldid -SSuccessionEntitlements.plist ./SuccessionRestore.app/SuccessionRestore
ldid -SSuccessionEntitlements.plist ./SuccessionRestore.app/hdik-armv7
ldid -SSuccessionEntitlements.plist ./SuccessionRestore.app/hdik-arm64
ldid -SSuccessionEntitlements.plist ./SuccessionRestore.app/hdik-arm64e
rm -f ./SuccessionRestore.app/embedded.mobileprovision
mkdir ./com.samgisaninja.SuccessionRestore
cp -r ./Template/* ./com.samgisaninja.SuccessionRestore/
mkdir com.samgisaninja.SuccessionRestore/Applications/
mv SuccessionRestore.app com.samgisaninja.SuccessionRestore/Applications/
sudo fakeroot chmod 6755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore
sudo fakeroot chmod 0755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/hdik-armv7
sudo fakeroot chmod 0755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/hdik-arm64
sudo fakeroot chmod 0755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/hdik-arm64e
rm -rf ./Build
rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
sudo fakeroot dpkg-deb -Zgzip -b com.samgisaninja.SuccessionRestore com.samgisaninja.successionrestore.deb && rm -r com.samgisaninja.SuccessionRestore

## Changes made by nobbele/4ppleCracker
