#!/bin/bash

sudo echo -n

echo "COMPILING 32-BIT..."
xcodebuild -target SuccessionRestore -xcconfig compile32.xcconfig -configuration Debug -quiet
mv ./Build/Debug-iphoneos/SuccessionRestore.app/SuccessionRestore ./SuccessionRestore32
rm -rf ./Build
rm -rf ./Index

echo "COMPILING 64-BIT"
xcodebuild -target SuccessionRestore -xcconfig compile64.xcconfig -configuration Debug -quiet
mv ./Build/Debug-iphoneos/SuccessionRestore.app ./
mv ./SuccessionRestore32 ./SuccessionRestore.app/SuccessionRestore32
ldid -SSuccessionEntitlements.plist ./SuccessionRestore.app/SuccessionRestore
ldid -SSuccessionEntitlements.plist ./SuccessionRestore.app/SuccessionRestore32
rm -f ./SuccessionRestore.app/embedded.mobileprovision
mkdir ./com.samgisaninja.SuccessionRestore
cp -r ./Template/* ./com.samgisaninja.SuccessionRestore/
mkdir com.samgisaninja.SuccessionRestore/Applications/
mv SuccessionRestore.app com.samgisaninja.SuccessionRestore/Applications/
sudo fakeroot chmod 6755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore
sudo fakeroot chmod 6755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore32
rm -rf ./Build
rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
sudo fakeroot dpkg-deb -Zgzip -b com.samgisaninja.SuccessionRestore com.samgisaninja.successionrestore.deb && rm -r com.samgisaninja.SuccessionRestore

if [ -z "$IDEVICEIP" ]
then
	echo "\$IDEVICEIP not found, please type in your iDevice's ip address (local for localhost:2222)"
	read IDEVICEIP
fi
if [ "$IDEVICEIP" == "local" ]
then
	echo "Trying to move deb to device"
	scp -p 2222 com.samgisaninja.SuccessionRestore.deb root@localhost:/tmp
	echo "Trying to install deb"
	ssh -p 2222 root@localhost "dpkg -i /tmp/com.samgisaninja.SuccessionRestore.deb && uicache"
	echo "Success!"
else
	echo "Trying to move deb to device"
	scp com.samgisaninja.SuccessionRestore.deb root@$IDEVICEIP:/tmp
	echo "Trying to install deb"
	ssh root@$IDEVICEIP "dpkg -i /tmp/com.samgisaninja.SuccessionRestore.deb && uicache"
	echo "Success!"
fi

## Changes made by nobbele/4ppleCracker
