#!/bin/bash
sudo echo -n
xcodebuild -target SuccessionRestore -configuration Release > .logs/xcode.log
mv ./Build/Release-iphoneos/SuccessionRestore.app ./
mv SuccessionRestore.app/SuccessionRestore SuccessionRestore.app/SuccessionRestore_
cp ./Template/Succ_Script ./SuccessionRestore.app/SuccessionRestore
rm -rf ./SuccessionRestore.app/_CodeSignature
ldid -S ./SuccessionRestore.app/SuccessionRestore_
rm -f ./SuccessionRestore.app/embedded.mobileprovision
mkdir ./com.samgisaninja.SuccessionRestore
cp -r ./Template/DEBIAN ./com.samgisaninja.SuccessionRestore/
mkdir com.samgisaninja.SuccessionRestore/Applications/
mv SuccessionRestore.app com.samgisaninja.SuccessionRestore/Applications/
sudo fakeroot chmod 755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore
sudo fakeroot chmod 6755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore_
rm -rf ./Build
rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
sudo fakeroot dpkg-deb -Zgzip -b com.samgisaninja.SuccessionRestore Debs && rm -r com.samgisaninja.SuccessionRestore
