#!/bin/bash

sudo echo -n

if [ -z "$SRDebug" ] 
then
  echo "\$SRDEBUG not set, using Debug as default"
  xcodebuild -target SuccessionRestore -configuration Debug > .logs/xcode.log
  mv ./Build/Debug-iphoneos/SuccessionRestore.app ./
else
  if [ $SRDebug == 1 ]
  then
    xcodebuild -target SuccessionRestore -configuration Debug > .logs/xcode.log
    mv ./Build/Debug-iphoneos/SuccessionRestore.app ./
  else
    xcodebuild -target SuccessionRestore -configuration Release > .logs/xcode.log
    mv ./Build/Release-iphoneos/SuccessionRestore.app ./
  fi
fi

mv SuccessionRestore.app/SuccessionRestore SuccessionRestore.app/SuccessionRestore_
cp ./Template/Succ_Script ./SuccessionRestore.app/SuccessionRestore
rm -rf ./SuccessionRestore.app/_CodeSignature
ldid -S ./SuccessionRestore.app/SuccessionRestore_
rm -f ./SuccessionRestore.app/embedded.mobileprovision
mkdir ./com.samgisaninja.SuccessionRestore
cp -r ./Template/DEBIAN ./com.samgisaninja.SuccessionRestore/
mkdir com.samgisaninja.SuccessionRestore/Applications/
mv SuccessionRestore.app com.samgisaninja.SuccessionRestore/Applications/
sudo fakeroot chmod 755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore
sudo fakeroot chmod 6755 com.samgisaninja.SuccessionRestore/Applications/SuccessionRestore.app/SuccessionRestore_
rm -rf ./Build
rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
sudo fakeroot dpkg-deb -Zgzip -b com.samgisaninja.SuccessionRestore com.samgisaninja.SuccessionRestore.deb && rm -r com.samgisaninja.SuccessionRestore

if [ -z "$IDEVICEIP" ] 
then
	echo "\$IDEVICEIP not found, please type in your iDevice's ip address"
	read IDEVICEIP
fi

scp com.samgisaninja.SuccessionRestore.deb root@$IDEVICEIP:/tmp
ssh root@$IDEVICEIP "dpkg -i /tmp/com.samgisaninja.SuccessionRestore.deb && uicache"

## Changes made by nobbele/4ppleCracker
