#define COLOUR_RESET "\e[0m"
#define COLOUR_YELLOW "\e[1;33m"
#define COLOUR_RED "\e[1;31m"
#define COLOUR_GREEN "\e[1;32m"
#define SUCCESSION_FOLDER "/private/var/mobile/Media/Succession"
#define CURRENT_SUCCESSION_VERSION "1.0~alpha0"