#!/bin/bash
mkdir /var/mobile/Media/Succession/
chmod 0777 /var/mobile/Media/Succession/
killall SuccessionRestore
if [ "$(uname -p)" == "arm" ]
then
echo "Succession has detected 32-bit!"
rm /Applications/SuccessionRestore.app/SuccessionRestore
mv /Applications/SuccessionRestore.app/SuccessionRestore32 /Applications/SuccessionRestore.app/SuccessionRestore
fi
if [ "$(uname -p)" == "arm64" ]
then
    echo "Succession has detected 64-bit!"
    rm /Applications/SuccessionRestore.app/SuccessionRestore32
fi
if [ ! -f /Applications/Setup.app/Setup ]; then
    if [ -f /Applications/Setup.app/Setup.bak ]; then
        mv /Applications/Setup.app/Setup.bak /Applications/Setup.app/Setup
    else
        touch /Applications/Setup.app/Setup
    fi
fi
echo "Succession by Sam Gardner // Samg_is_a_Ninja"
echo "Special Thanks to xerub, pwn20wnd, Cryptiiic, PsychoTea, uroboro, and 4ppleCracker"

exit 0
