#!/bin/bash
mkdir /var/mobile/Media/Succession/
chmod 0777 /var/mobile/Media/Succession/
echo "Succession: disabling Setup executable"
mv /Applications/Setup.app/Setup /Applications/Setup.app/Setup.bak
if [ "$(uname -p)" == "arm" ]
then
echo "Succession has detected 32-bit!"
rm /Applications/SuccessionRestore.app/SuccessionRestore
mv /Applications/SuccessionRestore.app/SuccessionRestore32 /Applications/SuccessionRestore.app/SuccessionRestore
fi
if [ "$(uname -p)" == "arm64" ]
then
    echo "Succession has detected 64-bit!"
    rm /Applications/SuccessionRestore.app/SuccessionRestore32
fi
echo "Succession by Sam Gardner // Samg_is_a_Ninja"
echo "Special Thanks to xerub, pwn20wnd, Cryptiiic, PsychoTea, uroboro, and 4ppleCracker"

exit 0
