#!/bin/bash
mkdir -p /var/mobile/Media/Succession/
chmod 0777 /var/mobile/Media/Succession/
echo "SuccessionCLI by Sam Gardner // Samg_is_a_Ninja and Hassan’s Tech // demhademha"
echo "Special Thanks to pwn20wnd and wh0ba"
echo "now run succession.sh to begin restoring"
exit 0